---
apiVersion: v1
kind: Service
metadata:
  name: daws-90s-catalogue
  namespace: {{ .Values.namespace }}
  # servicer labels
  labels:
    project: roboshop
    tier: backend
    component: daws-90s-catalogue
spec:
  # Service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: backend
    component: daws-90s-catalogue
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port